apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: first
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "3" # at least 3 replicas of first
    spec:
      containers:
        - image: atosh502/appender:latest
          env:
            - name: MESSAGE
              value: " - Handled by 0"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: second
spec:
  template:
    spec:
      containers:
        - image: atosh502/appender:latest
          env:
            - name: MESSAGE
              value: " - Handled by 1"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: third
spec:
  template:
    spec:
      containers:
        - image: atosh502/appender:latest
          env:
            - name: MESSAGE
              value: " - Handled by 2"
            - name: TYPE
              value: "samples.http.mod3"
---