Debug=1
# NumHeapPages=131072
# NumHeapPages=262144
NumHeapPages=413696
# NumHeapPages=524288
# NumHeapPages=2097152
NumStackPages=1024
# NumStackPages=2048
# NumStackPages=8192
# NumTCS=256
NumTCS=100
ProductID=1
SecurityVersion=1