apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: sequence
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: validate-fun-member
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: vote-fun-member
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: count-vote-fun-member
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: display-fun-member
  reply:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: broker